import streamlit as st
import requests
from deep_translator import GoogleTranslator

# Page Config
st.set_page_config(page_title="Sinhala AI Designer", page_icon="🎨")

# --- සරල Translator එකක් ---
def translate_to_english(text):
    try:
        translated = GoogleTranslator(source='auto', target='en').translate(text)
        return translated
    except:
        return text

def main():
    st.title("🎨 Sinhala AI Post Designer")
    st.write("සල්ලි වියදම් කරන්නේ නැතුව Image එකත් එක්කම Post හදාගන්න.")

    # 1. Topic/Subject (සිංහලෙන් හෝ ඉංග්‍රීසියෙන්)
    user_input = st.text_input("ඔයාගේ පෝස්ට් එක ගැන කෙටියෙන් ලියන්න (සිංහලෙන් වුණත් පුළුවන්)", placeholder="උදා: රසවත් බර්ගර් එකක්, ලස්සන ගෙයක්...")

    # 2. Localized Templates
    template = st.selectbox("මොන වගේ එකක්ද?", [
        "Normal (General)", 
        "Sri Lankan Food Style", 
        "Avurudu/Festival Theme", 
        "Business Promotion", 
        "WhatsApp Status Style"
    ])

    col1, col2 = st.columns(2)
    with col1:
        mood = st.selectbox("Mood", ["Luxury", "Vibrant", "Dark & Moody", "Cinematic"])
    with col2:
        ratio = st.selectbox("Size", ["1:1", "16:9", "9:16"])

    if st.button("Generate & View Image 🚀", use_container_width=True):
        if user_input:
            with st.spinner('පොඩ්ඩක් ඉන්න, වැඩේ කෙරෙනවා...'):
                # සිංහලෙන් ලිව්වා නම් translate කරනවා
                english_subject = translate_to_english(user_input)
                
                # Template එක අනුව prompt එක හැදීම
                templates_dict = {
                    "Sri Lankan Food Style": "Traditional Sri Lankan food style, highly detailed, professional food photography, warm lighting",
                    "Avurudu/Festival Theme": "Traditional Sri Lankan cultural festival style, vibrant colors, cultural motifs, celebratory mood",
                    "Business Promotion": "Clean professional corporate design, minimal, modern marketing style",
                    "WhatsApp Status Style": "Highly aesthetic, portrait photography, artistic bokeh",
                    "Normal (General)": "Professional digital art style"
                }

                final_prompt = f"{english_subject}, {templates_dict[template]}, {mood} mood, high resolution, 8k --ar {ratio}"
                
                # --- FREE IMAGE GENERATION (Pollinations API) ---
                # මේක සල්ලි යන්නේ නැති ලේසිම ක්‍රමය
                encoded_prompt = requests.utils.quote(final_prompt)
                image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true"

                st.divider()
                st.subheader("හදපු Prompt එක:")
                st.code(final_prompt)

                # Image එක පෙන්වීම
                st.image(image_url, caption="Generated by Free AI", use_container_width=True)
                
                # Download link for Image
                st.markdown(f"[📥 Image එක Download කරගන්න]({image_url})")
        else:
            st.warning("මුලින්ම මොකක් හරි දෙයක් ටයිප් කරන්න මචං!")

if __name__ == "__main__":
    main()
