name: Streamlit App Deploy

on:
  push:
    branches: [ "main" ]

# මෙන්න මේ කොටස එකතු කරන්න
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # මචං, පුළුවන් නම් මේක v5 වලට මාරු කරන්න

      - name: Set up Python
        uses: actions/setup-python@v5 # v3 වෙනුවට v5 පාවිච්චි කරන්න
        with:
          python-version: '3.11'

      # ... ඉතිරි ටික කලින් වගේමයි
